### ISSUE TITLE
Min Sdk Version

### ISSUE THREAD

**Issue by okarakose** [AnthonyFermin/DropDownView#3]
Hi,

You did great job with this library but I wonder why did you specified **minSdkVersion** as **19** ? if this can be decrease to 16 or 15 it would be great for a lot of developers which is considering to use this.

**Comment by AnthonyFermin** [comment]
Hi @okarakose, thanks for the compliment. Currently the minSdkVersion is set to 19 since the library uses the `TransitionManager` and it has no fallback animation for minSdkVersions lower than 19. The best bet would be to just replace the `TransitionManager` with `ObjectAnimator`. Most of my apps are 19 or up so I had no reason to lower it. Perhaps I'll have some time this weekend work on this.

**Comment by heckslam** [comment]
@AnthonyFermin Any news about this issue?

**Comment by okarakose** [comment]
@AnthonyFermin 

Lets forget api levels which are under 19. Google does not supporting them for security patches and they should be gone. I will increase my apps min sdk's from 15 to 18 for now.

Source : https://en.wikipedia.org/wiki/Android_version_history

Issue can be closed.
